#This program was created to parse text files
#generated by the NMFF echo database. 

#It inputs a text file (eventually a body of text files)
#and outputs an excel file with the data.

#For help, go to this readme: https://github.com/svsaraf/echoparser

#Gets the text file / folder that needs to be processed.
#FUNCTION DEFINITIONS:
from tempfile import TemporaryFile
from xlwt import Workbook
from time import localtime, strftime
import os
import sys
from xlrd import open_workbook, cellname, XL_CELL_EMPTY
import re
import odict
import pdb
#pdb.set_trace()

def processfile2(filename, sheet, inputdictionary):
	print "Analyzing " + filename
	originrow = 1
	origincol = 1
	datadictionary = {}
	f = open(filename, 'r')
	count = 0
	line = f.readline()
	while (line != ""):
	    newdict = line.split(': ')
	    for x in range(0, len(newdict)):
	    	sheet.write(originrow, origincol + x, newdict[x])
	    originrow+=1
	    line = f.readline()
	f.close()
	return datadictionary

def processfile(filename, sheet, inputdictionary, outputdictionary):
	print "Analyzing " + filename
	datadictionary = odict.odict()
	f = open(filename, 'r').read()
	for eachoutput in outputdictionary:
		datadictionary[eachoutput] = ''
	for var_name in inputdictionary:
		p = re.compile(re.escape(var_name) + ':*\s*', re.IGNORECASE)
		m = p.search(f)
		if m != None:
			if inputdictionary[var_name][1] == 'n':
				edited = f[m.end():]
				q = re.compile(r'\d+\s*/*\d*/*\d*\s*\d*\d*/*\d*')
				n = q.match(edited)
				if n != None:
					datadictionary[inputdictionary[var_name][0]] = n.group()
				else:
					datadictionary[inputdictionary[var_name][0]] = ''
			elif inputdictionary[var_name][1] == 'st':
				edited = f[m.end():]
				q = re.compile(r'\w+.*')
				n = q.match(edited)
				if n != None:
					datadictionary[inputdictionary[var_name][0]] = n.group()
				else:
					datadictionary[inputdictionary[var_name][0]] = ''
			elif inputdictionary[var_name][1] == 'ss':
				edited = f[m.end():]
				q = re.compile(r'[a-zA-Z]+?.*\n\s*\n')
				n = q.match(edited)
				if n != None:
					datadictionary[inputdictionary[var_name][0]] = n.group()
				else:
					datadictionary[inputdictionary[var_name][0]] = ''
		else: 
			datadictionary[var_name] = ''
	return datadictionary

def retrieveinputdictionary(inputdictionary):
	heading = ''
	book = open_workbook('inputparameters/inputparameters.xls', formatting_info=True)
	sheet = book.sheet_by_index(0)
	for row_index in range(sheet.nrows):
		if (row_index > 0):
			font = book.font_list
			cell_xf = book.xf_list[sheet.cell_xf_index(row_index,1)]
			if font[cell_xf.font_index].bold:
				inputdictionary[sheet.cell(row_index,1).value] = [sheet.cell(row_index,2).value, sheet.cell(row_index,3).value]
	return inputdictionary


timing = strftime("%Y-%m-%d %H:%M:%S", localtime())
folder = 0;
total = len(sys.argv)
if total == 1:
	sys.exit("I need an input file and a process type. Try python parser.py sample.txt")
filename = sys.argv[1]
inputdictionary = odict.odict()
inputdictionary = retrieveinputdictionary(inputdictionary)
#print "Length of input dict is " + str(len(inputdictionary))
#print inputdictionary
outputdictionary = odict.odict()
for inputkey in inputdictionary:
	outputdictionary[inputdictionary[inputkey][0]] = inputdictionary[inputkey][1]
#print "Length of output dict is " + str(len(outputdictionary))
#print outputdictionary
log = "Processing " + sys.argv[1] + " at " + timing
print log
book = Workbook(encoding='utf-8')
if sys.argv[total-1] == "folder":
	folder = 1;
	foldername = filename;
	sheet = book.add_sheet("OUTPUT")
	writtenrow = 0
	writtencol = 1
	for param in outputdictionary:
		sheet.write(writtenrow, writtencol, param)
		writtencol += 1
	writtenrow = 1
	writtencol = 0
	for f in os.listdir(foldername):
		if f[-4:] == ".txt":
			sheet.write(writtenrow, writtencol, f)
			datadictionary = processfile(foldername + "/" + f, sheet, inputdictionary, outputdictionary)
			for datapoint in datadictionary:
				writtencol+=1
				sheet.write(writtenrow, writtencol, datadictionary[datapoint])
			writtenrow += 1
			writtencol = 0

	timing = strftime("%Y-%m-%d %H:%M:%S", localtime())	
	log = "Processing complete at " + timing + "."
	sheet.write(0,0,log)

	book.save("output_" + foldername + ".xls")
	timing = strftime("%Y-%m-%d %H:%M:%S", localtime())
	print "Finished analyzing at " + timing + "."
else:
	folder = 0;
	sheet = book.add_sheet(filename)
	datadictionary = processfile(filename, sheet, inputdictionary)
	sheet.write(0,0,log)
	book.save("output_" + filename[:-4] + ".xls")
	timing = strftime("%Y-%m-%d %H:%M:%S", localtime())
	print "Finished analyzing at " + timing + "."








