#This program was created to parse text files
#generated by the NMFF echo database. 

#It inputs a text file (eventually a body of text files)
#and outputs an excel file with the data.


#Gets the text file that needs to be processed.
import sys
total = len(sys.argv)
if total == 1:
	sys.exit("I need an input file! Try python parser.py sample.txt")
filename = sys.argv[total-1]
print "Processing " + sys.argv[total-1]

#Opens the input file, creates the dictionary.
dictionary = {}
f = open(filename, 'r')
count = 0
line = f.readline()
while (line != ""):
    print line
    newdict = line.split(': ')
    print newdict
    count+=1
    line = f.readline()

print "count =" + str(count)


